from dash import dcc
from dash import html

import dash_bootstrap_components as dbc
menu = None

body = [
    dbc.Row(dbc.Col(
        dbc.Card([
            dbc.CardHeader(html.H2("Download Sample h5ad File")),
            dbc.CardBody(
                dbc.Row([
                    dbc.Col(dcc.Markdown(''' A h5ad file is a file format used for storing and manipulating single-cell gene expression data in a highly efficient manner. The h5ad file format is based on the Hierarchical Data Format version 5 (HDF5) file format, which is designed to support large and complex datasets.
                    The h5ad file contains a compressed and indexed version of the Anndata file format. It contains information on the gene expression levels for each cell in the dataset, as well as information on the genes themselves, such as their names, IDs, and annotations.''')),
                    dbc.Col([
                        # html.Img(src='assets/anndata_schema.png', height=300),html.Br(),html.Br(),
                        html.Button("Download h5ad file", id="download-h5ad-button"), dcc.Download(id="download-h5ad")]),
                ])
            ),
        ],),
    ),class_name="mb-4 mt-4"),
    dbc.Row( dbc.Col(
        dbc.Card([
            dbc.CardHeader(html.H2("Download Sample 10X zip Files")),
            dbc.CardBody(
                dbc.Row([
                    dbc.Col(dcc.Markdown(''' The 10x files refer to a zip file format used to store single-cell gene expression data generated by the 10x Genomics platform. The 10x file typically contains a list of barcodes and their corresponding gene expression values for each cell in the dataset. In addition, the file may also contain information on the genes themselves, such as their names, IDs, and annotations.''')),
                    dbc.Col([
                        # html.Img(src='assets/anndata_schema.png', height=300),html.Br(),html.Br(),
                        html.Button("Download 10x zip file", id="download-10x-button"), dcc.Download(id="download-10x")]),
                ])
            ),
        ], ),
    ),class_name="mb-4 mt-4"),
    dbc.Row( dbc.Col(
        dbc.Card([
            dbc.CardHeader(html.H2("Download Sample h5 Files")),
            dbc.CardBody(
                dbc.Row([
                    dbc.Col(dcc.Markdown(''' An h5 file, also known as an HDF5 file, is a file format used to store and manage large and complex datasets. HDF5 stands for Hierarchical Data Format version 5, and it is a versatile file format that allows for efficient storage, retrieval, and analysis of data.''')),
                    dbc.Col([
                        # html.Img(src='assets/anndata_schema.png', height=300),html.Br(),html.Br(),
                        html.Button("Download h5 file", id="download-h5-button"), dcc.Download(id="download-h5")]),
                ])
            ),
        ], ),
    ),class_name="mb-4 mt-4"),
]
